### PR TITLE
Add navigation

### PR DESCRIPTION
**Pull request by NicolasHeine**

### CODE REVIEW

**Comment by nm-t** [comment]
Very nice @NicolasHeine! Thank you! It looks like there's a conflict though - are you able to resolve this before we merge?

**Comment by josh-** [comment]
@NicolasHeine will close this conflicting PR, but thanks so much for your work and definitely open a new PR if you'd like! 🙌

**Comment by NicolasHeine** [comment]
Oh sorry I forgot it... I was pretty busy yesterday so I did not have time
to fix it... sorry

Heine Nicolas

Le dim. 21 oct. 2018 à 15:14, Josh Parnham <notifications@github.com> a
écrit :

**Comment by josh-** [comment]
Absolutely no worries at all @NicolasHeine - really appreciate your contribution! 🎉

**Pull request closed without merging**
